default_context:
  project_name: 'chili'
  project_slug: 'chili'
  domain_main: 'chili.com'
  domain_staging: 'stag.chili.com'
  docker_swarm_stack_name_main: 'chili-com'
  docker_swarm_stack_name_staging: 'stag-chili-com'
  secret_key: '6e184d47ebb8b875d0eee7a16dd97e6906b45c3529f0c78382f840e215414b66'
  first_superuser: 'admin@chili.com'
  first_superuser_password: '553bda9b7b1a27893b5a4311709e44147d7e7538413ff2be3e88a4d2ab3e5f3f'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.chili.com", "https://stag.chili.com", "https://chili.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@chili.com'
  postgres_password: '0a7e513e764709175a984074eb7f72a7b331ad51d902275aecf90c7462885c90'
  pgadmin_default_user: 'admin@chili.com'
  pgadmin_default_user_password: '553bda9b7b1a27893b5a4311709e44147d7e7538413ff2be3e88a4d2ab3e5f3f'
  traefik_constraint_tag: 'chili.com'
  traefik_constraint_tag_staging: 'stag.chili.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:553bda9b7b1a27893b5a4311709e44147d7e7538413ff2be3e88a4d2ab3e5f3f'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
