"""upd

Revision ID: 1ff0bd71da13
Revises: eafd89ab1a4c
Create Date: 2021-10-09 19:44:32.965619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff0bd71da13'
down_revision = 'eafd89ab1a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
