"""username field

Revision ID: 462099e81817
Revises: 1ff0bd71da13
Create Date: 2021-10-14 03:01:30.668093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462099e81817'
down_revision = '1ff0bd71da13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
