"""category slug field

Revision ID: 5762c239f98f
Revises: 8456c5714a7a
Create Date: 2021-10-15 15:22:05.360811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5762c239f98f'
down_revision = '8456c5714a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
