"""category_title

Revision ID: 8456c5714a7a
Revises: 462099e81817
Create Date: 2021-10-14 11:21:51.717458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8456c5714a7a'
down_revision = '462099e81817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'title')
    # ### end Alembic commands ###
