"""product slug field

Revision ID: 8596a0c10215
Revises: 5762c239f98f
Create Date: 2021-10-18 14:58:41.495565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8596a0c10215'
down_revision = '5762c239f98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_column('product', 'slug')
    # ### end Alembic commands ###
